# example config file from mac-dev-playbook, just to provide a basic idea of what to configure

downloads: ~/.ansible-downloads/
# https://github.com/juju4/ansible-macos-apps-install

# Setup Oh-my-zsh
macos_ohmyzsh:
  # Set zsh as default shell
  default: false  # it's already a default shell in new macOS versions
  # Configure oh-my-zsh after install?
  configure: false

configure_dotfiles: true
configure_terminal: false
configure_sudoers: false
configure_sublime: false
configure_osx: true

dotfiles_repo: git@github.com:Bobronium/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dev/meta/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .inputrc
  - .macos

homebrew_installed_packages:
  - aws-iam-authenticator
  - awscli
  - bash-completion
  - caddy
  - cowsay
  - git
  - github/gh/gh
  - go
  - google-chrome
  - httpie
  - iterm2
  - jq
  - k9s
  - kubernetes-cli
  - libxml2
  - mas
  - micro
  - node
  - notion
  - sqlite
  - ssh-copy-id
  - openssl@3
  - pv
  - pyenv
  - rust
  - wget
  - zlib

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

osx_script: "bash ~/.macos --no-restart"

mas_installed_apps:
  - { id: 1024640650, name: "CotEditor" }
  - { id: 803453959, name: "Slack" }
  - { id: 1017470484, name: "Next Meeting" }
  - { id: 430255202, name: "Mactracker" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 408981434, name: "iMovie" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1476085650, name: "FastClip" }


configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - TV
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Podcasts
  - Keynote
  - Numbers
  - Pages
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 2


# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
